# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reference_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Reference(object):
    def setupUi(self, Reference):
        Reference.setObjectName("Reference")
        Reference.setEnabled(True)
        Reference.resize(412, 355)
        Reference.setMinimumSize(QtCore.QSize(412, 355))
        Reference.setMaximumSize(QtCore.QSize(412, 355))
        self.label = QtWidgets.QLabel(Reference)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 0, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(Reference)
        self.textBrowser.setGeometry(QtCore.QRect(10, 40, 391, 301))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Reference)
        QtCore.QMetaObject.connectSlotsByName(Reference)

    def retranslateUi(self, Reference):
        _translate = QtCore.QCoreApplication.translate
        Reference.setWindowTitle(_translate("Reference", "Form"))
        self.label.setText(_translate("Reference", "Справка"))
        self.textBrowser.setHtml(_translate("Reference", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">1. &quot;Вывод видео&quot; - вывод видеопотока с камеры с ключевыми обозначениями (см. пункт 4).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">2. &quot;Использование указки&quot; - управление указкой с помощью указательного пальца выбранной руки (настройка в выпадающем списке ниже). Комбинация клавиш, которая включает указку в используемом приложении для презентации выбирается в выпадающем списке с клавишами). Для включения указки рукой для управления проведите от лица вверх.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">3. Если не включён пункт &quot;Использование указки&quot;, выберите руку, которая будет управлять презентацией (включение следующего или предыдущего слайда). Для листания слайдов проведите ладонью для управления от лица влево, чтобы переключиться на предыдущий слайд; от лица вправо, чтобы переключиться на следующий слайд.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">4. Ключевые обозначения на видео - определение указательного пальца правой (белый поинт на пальце) или левой (жёлтый поинт на пальце) руки. При включённой указки выводится сообщение &quot;Указка включена&quot; на выводе потока видео, указательный палец руки, используемой для указки, выделяется красным поинтом. При переключении слайдов выводится сообщение &quot;Вперёд&quot; или &quot;Назад&quot; на выводе потока видео. Если рука для управления находится в меньшем прямоугольнике, то при перемещении ладони из этого прямоугольника в определённую сторону включится команда (см. пункт 3).</span></p></body></html>"))
